Harden pyclient release workflow gating

diff --git a/.github/workflows/ci-workflow.yml b/.github/workflows/ci-workflow.yml
--- a/.github/workflows/ci-workflow.yml
+++ b/.github/workflows/ci-workflow.yml
@@ -194,10 +194,31 @@ jobs:
           name: benchmarks-log
           path: tests_perf/benchmarks.json
 
+  deploy_python_client_check_tag:
+    name: Check that pyclient tag matches ledger_bitcoin version
+    needs: job_test_python_lib_legacyapp
+    runs-on: ubuntu-latest
+    if: success() && github.event_name == 'push' && startsWith(github.ref, 'refs/tags/pyclient-')
+    steps:
+      - name: Clone
+        uses: actions/checkout@v4
+
+      - name: Check that tag matches __version__
+        run: |
+            package_version=$(sed -n -E "s/^__version__ = \"([0-9]+\.[0-9]+\.[0-9]+)\"/\1/p" bitcoin_client/ledger_bitcoin/__init__.py)
+            tag_version=${GITHUB_REF#refs/tags/pyclient-}
+            if [[ $package_version == $tag_version ]]; then
+                echo "[INFO] Tag matches ledger_bitcoin.__version__. Continuing."
+            else
+                echo "[ERROR] mismatch between version in tag and ledger_bitcoin.__version__. Aborting."
+                exit 1
+            fi
+
   python_package_and_deploy:
     name: Build and deploy the bitcoin client Python package
+    needs: deploy_python_client_check_tag
     uses: LedgerHQ/ledger-app-workflows/.github/workflows/reusable_pypi_deployment.yml@v1
-    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/pyclient')
+    if: success() && github.event_name == 'push' && startsWith(github.ref, 'refs/tags/pyclient-')
     with:
       package_name: ledger_bitcoin
       package_directory: ./bitcoin_client/
